name: Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - folder: "dist/prod"
            branch: "dist"
            npmrunparam: "build"
          - folder: "dist/sandbox"
            branch: "dist-sandbox"
            npmrunparam: "buildsandbox"
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - name: Install dependencies
      run: npm install
    - name: Build files
      run: npm run ${{ matrix.npmrunparam }}
    - name: Commit built files to the ${{ matrix.branch }} branch
      if:  github.ref == 'refs/heads/master'
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: ${{ matrix.branch }}
        FOLDER: ${{ matrix.folder }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
